anchor_version = "0.24.2"

[features]
seeds = false

[programs.localnet]
amm_v3 = "devKfPVu9CaDvG47KG7bDKexFvAY37Tgp6rPHTruuqU"

[programs.devnet]
amm_v3 = "devKfPVu9CaDvG47KG7bDKexFvAY37Tgp6rPHTruuqU"


[registry]
url = "https://github.com/raydium-io/raydium-amm-v3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json" 

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 100000 tests/**/*.ts"

[test]
startup_wait = 20000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./external-programs/spl_token_metadata.so"